# cards_data.py

CARDS = [
    # ===== 天罡36 =====
    {"id": 1, "name": "宋江", "nick": "呼保义", "atk": 80, "def": 20, "lead": 91, "might": 51, "intel": 76, "politics": 81, "charm": 99,
     "info": "山东郓城县宋家村人氏，梁山泊第三代寨主"},
    {"id": 2, "name": "卢俊义", "nick": "玉麒麟", "atk": 98, "def": 50, "lead": 76, "might": 98, "intel": 44, "politics": 48, "charm": 86,
     "info": "北京大名府人氏，梁山泊第二总兵都头领"},
    {"id": 3, "name": "吴用", "nick": "智多星", "atk": 90, "def": 5, "lead": 71, "might": 34, "intel": 94, "politics": 81, "charm": 72,
     "info": "山东济州郓城县东溪村人氏，梁山泊掌管机密军师，位列第三"},
    {"id": 4, "name": "公孙胜", "nick": "入云龙", "atk": 95, "def": 5, "lead": 58, "might": 64, "intel": 95, "politics": 59, "charm": 88,
     "info": "蓟州九宫县人氏，梁山泊掌管机密军师（副军师）位列第四"},
    {"id": 5, "name": "关胜", "nick": "大刀", "atk": 88, "def": 65, "lead": 86, "might": 96, "intel": 83, "politics": 52, "charm": 93,
     "info": "河东解良（今山西运城）人氏，梁山泊马军五虎将之首，位列第五"},
    {"id": 6, "name": "林冲", "nick": "豹子头", "atk": 95, "def": 60, "lead": 77, "might": 94, "intel": 79, "politics": 62, "charm": 81,
     "info": "东京（今河南开封）人氏，梁山泊马军五虎将之一，位列第六"},
    {"id": 7, "name": "秦明", "nick": "霹雳火", "atk": 85, "def": 65, "lead": 74, "might": 91, "intel": 31, "politics": 38, "charm": 52,
     "info": "山后开州人氏，梁山泊马军五虎将之一，位列第七"},
    {"id": 8, "name": "呼延灼", "nick": "双鞭", "atk": 95, "def": 65, "lead": 80, "might": 92, "intel": 57, "politics": 45, "charm": 64,
     "info": "并州太原人氏，梁山泊马军五虎将第四员，位列第八"},
    {"id": 9, "name": "花荣", "nick": "小李广", "atk": 80, "def": 65, "lead": 72, "might": 90, "intel": 75, "politics": 60, "charm": 79,
     "info": "山东青州清风寨人氏，梁山泊马军八虎骑兼先锋使第一员，位列第九"},
    {"id": 10, "name": "柴进", "nick": "小旋风", "atk": 78, "def": 30, "lead": 74, "might": 70, "intel": 82, "politics": 84, "charm": 95,
     "info": "沧州横海郡人氏，梁山泊掌管钱粮头领，位列第十"},
    {"id": 11, "name": "李应", "nick": "扑天雕", "atk": 80, "def": 25, "lead": 73, "might": 88, "intel": 67, "politics": 79, "charm": 84,
     "info": "郓州独龙岗人氏，梁山泊掌管钱粮头领，位列第十一"},
    {"id": 12, "name": "朱仝", "nick": "美髯公", "atk": 83, "def": 40, "lead": 71, "might": 85, "intel": 78, "politics": 73, "charm": 91,
     "info": "山东济州郓城县人氏，梁山泊马军八骠骑兼先锋使，位列第十二"},
    {"id": 13, "name": "鲁智深", "nick": "花和尚", "atk": 88, "def": 45, "lead": 80, "might": 94, "intel": 69, "politics": 55, "charm": 88,
     "info": "渭州（今甘肃平凉）人氏，原为渭州经略府提辖，梁山泊步军头领，位列第十三"},
    {"id": 14, "name": "武松", "nick": "行者", "atk": 88, "def": 45, "lead": 70, "might": 94, "intel": 82, "politics": 72, "charm": 85,
     "info": "清河县人氏，梁山泊步军头领，位列第十四"},
    {"id": 15, "name": "董平", "nick": "双枪将", "atk": 93, "def": 34, "lead": 69, "might": 93, "intel": 38, "politics": 33, "charm": 58,
     "info": "河东上党郡人氏，梁山泊马军五虎将第五员，位列第十五"},
    {"id": 16, "name": "张清", "nick": "没羽箭", "atk": 81, "def": 18, "lead": 72, "might": 84, "intel": 75, "politics": 68, "charm": 85,
     "info": "彰德府人氏，梁山泊马军八骠骑兼先锋使第五员，位列第十六"},
    {"id": 17, "name": "杨志", "nick": "青面兽", "atk": 85, "def": 40, "lead": 62, "might": 90, "intel": 38, "politics": 27, "charm": 52,
     "info": "山西太原人氏，梁山泊马军八骠骑兼先锋使，位列第十七"},
    {"id": 18, "name": "徐宁", "nick": "金枪手", "atk": 85, "def": 90, "lead": 71, "might": 87, "intel": 56, "politics": 65, "charm": 83,
     "info": "东京人氏，梁山泊马军八骠骑兼先锋使第二员，位列第十八"},
    {"id": 19, "name": "索超", "nick": "急先锋", "atk": 87, "def": 60, "lead": 75, "might": 87, "intel": 41, "politics": 45, "charm": 64,
     "info": "河北大名府人氏，梁山泊马军八骠骑兼先锋使，位列第十九"},
    {"id": 20, "name": "戴宗", "nick": "神行太保", "atk": 85, "def": 40, "lead": 46, "might": 44, "intel": 76, "politics": 84, "charm": 50,
     "info": "江州人氏，梁山泊总探声息头领，位列第二十"},
    {"id": 21, "name": "刘唐", "nick": "赤发鬼", "atk": 82, "def": 20, "lead": 65, "might": 85, "intel": 58, "politics": 29, "charm": 57,
     "info": "山西潞州人氏（祖籍东潞州），梁山泊步军头领，位列第二十一"},
    {"id": 22, "name": "李逵", "nick": "黑旋风", "atk": 88, "def": 45, "lead": 69, "might": 86, "intel": 25, "politics": 1, "charm": 6,
     "info": "沂州沂水县百丈村人氏，梁山泊步军头领，位列第二十二"},
    {"id": 23, "name": "史进", "nick": "九纹龙", "atk": 70, "def": 35, "lead": 73, "might": 85, "intel": 48, "politics": 63, "charm": 80,
     "info": "华州华阴县人氏，梁山泊马军八骠骑兼先锋使，位列第二十三"},
    {"id": 24, "name": "穆弘", "nick": "没遮拦", "atk": 83, "def": 30, "lead": 70, "might": 80, "intel": 59, "politics": 67, "charm": 74,
     "info": "江州揭阳镇人氏，梁山泊马军八骠骑兼先锋使，位列第二十四"},
    {"id": 25, "name": "雷横", "nick": "插翅虎", "atk": 82, "def": 40, "lead": 70, "might": 78, "intel": 42, "politics": 60, "charm": 46,
     "info": "山东济州郓城县人氏，梁山泊步军头领，位列第二十五"},
    {"id": 26, "name": "李俊", "nick": "混江龙", "atk": 85, "def": 15, "lead": 80, "might": 76, "intel": 84, "politics": 78, "charm": 82,
     "info": "庐州人氏，梁山泊水军头领，位列第二十六"},
    {"id": 27, "name": "阮小二", "nick": "立地太岁", "atk": 82, "def": 15, "lead": 64, "might": 74, "intel": 63, "politics": 35, "charm": 61,
     "info": "济州梁山泊边石碣村人氏，梁山泊四寨水军头领，位列第二十七"},
    {"id": 28, "name": "张横", "nick": "船火儿", "atk": 80, "def": 15, "lead": 60, "might": 73, "intel": 34, "politics": 48, "charm": 39,
     "info": "江州小孤山人氏，梁山泊四寨水军头领，位列第二十八"},
    {"id": 29, "name": "阮小五", "nick": "短命二郎", "atk": 80, "def": 15, "lead": 64, "might": 75, "intel": 39, "politics": 33, "charm": 55,
     "info": "济州石碣村人氏，梁山泊四寨水军头领，位列第二十九"},
    {"id": 30, "name": "张顺", "nick": "浪里白跳", "atk": 80, "def": 15, "lead": 66, "might": 74, "intel": 77, "politics": 65, "charm": 83,
     "info": "江州人氏，梁山泊四寨水军头领，位列第三十"},
    {"id": 31, "name": "阮小七", "nick": "活阎罗", "atk": 80, "def": 15, "lead": 66, "might": 77, "intel": 40, "politics": 35, "charm": 83,
     "info": "济州石碣村人氏，梁山泊四寨水军头领，位列第三十一"},
    {"id": 32, "name": "杨雄", "nick": "病关索", "atk": 80, "def": 20, "lead": 63, "might": 84, "intel": 22, "politics": 42, "charm": 62,
     "info": "河南府人氏，梁山泊步军头领，位列第三十二"},
    {"id": 33, "name": "石秀", "nick": "拼命三郎", "atk": 82, "def": 20, "lead": 62, "might": 82, "intel": 79, "politics": 66, "charm": 75,
     "info": "金陵建康府人氏，梁山泊步军头领，位列第三十三"},
    {"id": 34, "name": "解珍", "nick": "两头蛇", "atk": 80, "def": 40, "lead": 60, "might": 75, "intel": 63, "politics": 33, "charm": 64,
     "info": "登州人氏，梁山泊步军头领，位列第三十四"},
    {"id": 35, "name": "解宝", "nick": "双尾蝎", "atk": 80, "def": 40, "lead": 60, "might": 77, "intel": 51, "politics": 35, "charm": 68,
     "info": "登州人氏，梁山泊步军头领，位列第三十五"},
    {"id": 36, "name": "燕青", "nick": "浪子", "atk": 45, "def": 45, "lead": 57, "might": 75, "intel": 86, "politics": 82, "charm": 93,
     "info": "北京大名府人氏，梁山泊步军头领，位列第三十六"},

    # ===== 地煞72 =====
    {"id": 37, "name": "朱武", "nick": "神机军师", "atk": 70, "def": 10, "lead": 68, "might": 55, "intel": 79, "politics": 76, "charm": 72,
     "info": "定远县人氏，梁山泊同参赞军务头领，位列第三十七"},
    {"id": 38, "name": "黄信", "nick": "镇三山", "atk": 79, "def": 29, "lead": 69, "might": 74, "intel": 69, "politics": 53, "charm": 61,
     "info": "青州人氏，梁山泊马军小彪将兼远探出哨头领，位列第三十八"},
    {"id": 39, "name": "孙立", "nick": "病尉迟", "atk": 77, "def": 38, "lead": 75, "might": 84, "intel": 67, "politics": 61, "charm": 62,
     "info": "琼州（今海南岛）人氏，梁山泊马军小彪将兼远探出哨头领，位列第三十九"},
    {"id": 40, "name": "宣赞", "nick": "丑郡马", "atk": 74, "def": 32, "lead": 69, "might": 82, "intel": 44, "politics": 48, "charm": 15,
     "info": "东京人氏，梁山泊马军小彪将兼远探出哨头领，位列第四十"},
    {"id": 41, "name": "郝思文", "nick": "井木犴", "atk": 70, "def": 25, "lead": 65, "might": 79, "intel": 55, "politics": 53, "charm": 72,
     "info": "东京人氏，梁山泊马军小彪将兼远探出哨头领，位列第四十一"},
    {"id": 42, "name": "韩滔", "nick": "百胜将", "atk": 46, "def": 33, "lead": 68, "might": 73, "intel": 63, "politics": 53, "charm": 71,
     "info": "东京人氏，梁山泊马军小彪将兼远探出哨头领，位列第四十二"},
    {"id": 43, "name": "彭玘", "nick": "天目将", "atk": 71, "def": 32, "lead": 65, "might": 72, "intel": 57, "politics": 56, "charm": 71,
     "info": "东京人氏，梁山泊马军小彪将兼远探出哨头领，位列第四十三"},
    {"id": 44, "name": "单廷珪", "nick": "圣水将", "atk": 72, "def": 20, "lead": 74, "might": 77, "intel": 62, "politics": 54, "charm": 75,
     "info": "凌州人氏，梁山泊马军小彪将兼远探出哨头领，位列第四十四"},
    {"id": 45, "name": "魏定国", "nick": "神火将", "atk": 75, "def": 22, "lead": 76, "might": 79, "intel": 67, "politics": 32, "charm": 72,
     "info": "凌州人氏，梁山泊马军小彪将兼远探出哨头领，位列第四十五"},
    {"id": 46, "name": "萧让", "nick": "圣手书生", "atk": 39, "def": 10, "lead": 27, "might": 50, "intel": 71, "politics": 77, "charm": 75,
     "info": "济州人氏，梁山泊掌管监造诸事头领，负责行文走檄调兵遣将，位列第四十六"},
    {"id": 47, "name": "裴宣", "nick": "铁面孔目", "atk": 62, "def": 27, "lead": 58, "might": 63, "intel": 72, "politics": 80, "charm": 84,
     "info": "京兆府人氏，梁山泊掌管监造诸事头领，负责定功赏罚军政司，位列第四十七"},
    {"id": 48, "name": "欧鹏", "nick": "摩云金翅", "atk": 65, "def": 25, "lead": 68, "might": 75, "intel": 57, "politics": 31, "charm": 69,
     "info": "黄州人氏，梁山泊马军小彪将兼远探出哨头领，位列第四十八"},
    {"id": 49, "name": "邓飞", "nick": "火眼狻猊", "atk": 67, "def": 25, "lead": 63, "might": 73, "intel": 49, "politics": 35, "charm": 78,
     "info": "盖天军襄阳府人氏，梁山泊马军小彪将兼远探出哨头领，位列第四十九"},
    {"id": 50, "name": "燕顺", "nick": "锦毛虎", "atk": 63, "def": 27, "lead": 67, "might": 68, "intel": 52, "politics": 56, "charm": 53,
     "info": "莱州人氏，梁山泊马军小彪将兼远探出哨头领，位列第五十"},
    {"id": 51, "name": "杨林", "nick": "锦豹子", "atk": 69, "def": 30, "lead": 62, "might": 71, "intel": 72, "politics": 66, "charm": 65,
     "info": "彰德府人氏，梁山泊马军小彪将兼远探出哨头领，位列第五十一"},
    {"id": 52, "name": "凌振", "nick": "轰天雷", "atk": 83, "def": 11, "lead": 57, "might": 65, "intel": 68, "politics": 73, "charm": 66,
     "info": "燕陵人氏，梁山泊掌管监造诸事头领，负责监造大小火炮，位列第五十二"},
    {"id": 53, "name": "蒋敬", "nick": "神算子", "atk": 42, "def": 21, "lead": 34, "might": 45, "intel": 70, "politics": 82, "charm": 65,
     "info": "潭州人氏，梁山泊掌管监造诸事头领，负责考算钱粮支出纳入，位列第五十三"},
    {"id": 54, "name": "吕方", "nick": "小温侯", "atk": 71, "def": 22, "lead": 64, "might": 79, "intel": 52, "politics": 40, "charm": 80,
     "info": "潭州人氏，梁山泊守护中军马军骁将，位列第五十四"},
    {"id": 55, "name": "郭盛", "nick": "赛仁贵", "atk": 71, "def": 22, "lead": 61, "might": 76, "intel": 62, "politics": 42, "charm": 76,
     "info": "西川嘉陵人氏，梁山泊守护中军马军骁将，位列第五十五"},
    {"id": 56, "name": "安道全", "nick": "神医", "atk": 30, "def": 15, "lead": 8, "might": 25, "intel": 69, "politics": 75, "charm": 87,
     "info": "建康府人氏，梁山泊掌管监造诸事头领，负责专治诸疾内外科医士，位列第五十六"},
    {"id": 57, "name": "皇甫端", "nick": "紫髯伯", "atk": 37, "def": 10, "lead": 9, "might": 37, "intel": 64, "politics": 78, "charm": 73,
     "info": "祖籍幽州人氏，梁山泊掌管监造诸事头领，负责专攻医兽一应马匹，位列第五十七"},
    {"id": 58, "name": "王英", "nick": "矮脚虎", "atk": 69, "def": 29, "lead": 60, "might": 64, "intel": 28, "politics": 20, "charm": 9,
     "info": "两淮人氏，梁山泊专掌三军内探事马军头领，位列第五十八"},
    {"id": 59, "name": "扈三娘", "nick": "一丈青", "atk": 75, "def": 35, "lead": 68, "might": 75, "intel": 67, "politics": 53, "charm": 82,
     "info": "郓州扈家庄人氏，梁山泊专掌三军内探事马军头领，位列第五十九"},
    {"id": 60, "name": "鲍旭", "nick": "丧门神", "atk": 67, "def": 37, "lead": 61, "might": 78, "intel": 20, "politics": 12, "charm": 8,
     "info": "寇州人氏，梁山泊步军将校，位列第六十"},
    {"id": 61, "name": "樊瑞", "nick": "混世魔王", "atk": 90, "def": 15, "lead": 72, "might": 73, "intel": 76, "politics": 45, "charm": 68,
     "info": "濮州人氏，梁山泊步军将校，位列第六十一"},
    {"id": 62, "name": "孔明", "nick": "毛头星", "atk": 35, "def": 25, "lead": 57, "might": 55, "intel": 36, "politics": 54, "charm": 48,
     "info": "青州人氏，梁山泊守护中军步军骁将，位列第六十二"},
    {"id": 63, "name": "孔亮", "nick": "独火星", "atk": 30, "def": 15, "lead": 52, "might": 53, "intel": 34, "politics": 40, "charm": 52,
     "info": "青州人氏，梁山泊守护中军步军骁将，位列第六十三"},
    {"id": 64, "name": "项充", "nick": "八臂哪吒", "atk": 55, "def": 30, "lead": 62, "might": 73, "intel": 45, "politics": 33, "charm": 52,
     "info": "徐州沛县人氏，梁山泊步军将校，位列第六十四"},
    {"id": 65, "name": "李衮", "nick": "飞天大圣", "atk": 55, "def": 30, "lead": 64, "might": 74, "intel": 33, "politics": 35, "charm": 51,
     "info": "邳州人氏，梁山泊步军将校，位列第六十五"},
    {"id": 66, "name": "金大坚", "nick": "玉臂匠", "atk": 40, "def": 14, "lead": 31, "might": 52, "intel": 65, "politics": 77, "charm": 71,
     "info": "济州人氏，梁山泊掌管监造诸事头领，负责专造一应兵符印信，位列第六十六"},
    {"id": 67, "name": "马麟", "nick": "铁笛仙", "atk": 75, "def": 15, "lead": 64, "might": 75, "intel": 59, "politics": 63, "charm": 60,
     "info": "南京建康人氏，梁山泊马军小彪将兼远探出哨头领，位列第六十七"},
    {"id": 68, "name": "童威", "nick": "出洞蛟", "atk": 60, "def": 26, "lead": 54, "might": 67, "intel": 64, "politics": 39, "charm": 48,
     "info": "浔阳江人氏，梁山泊四寨水军头领，位列第六十八"},
    {"id": 69, "name": "童猛", "nick": "翻江蜃", "atk": 60, "def": 20, "lead": 52, "might": 66, "intel": 55, "politics": 57, "charm": 50,
     "info": "浔阳江人氏，梁山泊四寨水军头领，位列第六十九"},
    {"id": 70, "name": "孟康", "nick": "玉幡竿", "atk": 38, "def": 10, "lead": 48, "might": 62, "intel": 64, "politics": 76, "charm": 79,
     "info": "真定州人氏，梁山泊掌管监造诸事头领，负责监造战船，位列第七十"},
    {"id": 71, "name": "侯健", "nick": "通背猿", "atk": 50, "def": 10, "lead": 25, "might": 50, "intel": 69, "politics": 71, "charm": 54,
     "info": "洪都人氏，梁山泊掌管监造诸事头领，负责专造一应旌旗袍袄，位列第七十一"},
    {"id": 72, "name": "陈达", "nick": "跳涧虎", "atk": 45, "def": 15, "lead": 62, "might": 67, "intel": 20, "politics": 18, "charm": 35,
     "info": "邺城人氏，梁山泊马军小彪将兼远探出哨头领，位列第七十二"},
    {"id": 73, "name": "杨春", "nick": "白花蛇", "atk": 40, "def": 15, "lead": 60, "might": 67, "intel": 32, "politics": 29, "charm": 18,
     "info": "蒲州解良人氏，梁山泊马军小彪将兼远探出哨头领，位列第七十三"},
    {"id": 74, "name": "郑天寿", "nick": "白面郎君", "atk": 49, "def": 22, "lead": 56, "might": 64, "intel": 52, "politics": 45, "charm": 73,
     "info": "苏州人氏，梁山泊步军将校，位列第七十四"},
    {"id": 75, "name": "陶宗旺", "nick": "九尾龟", "atk": 45, "def": 65, "lead": 48, "might": 65, "intel": 28, "politics": 52, "charm": 47,
     "info": "光州人氏，梁山泊掌管监造诸事头领，负责监修城池、筑补道路，位列第七十五"},
    {"id": 76, "name": "宋清", "nick": "铁扇子", "atk": 46, "def": 20, "lead": 29, "might": 31, "intel": 51, "politics": 53, "charm": 70,
     "info": "郓城县宋家村人氏，梁山泊掌管专一排设筵宴头领，位列第七十六"},
    {"id": 77, "name": "乐和", "nick": "铁叫子", "atk": 26, "def": 25, "lead": 40, "might": 54, "intel": 74, "politics": 70, "charm": 82,
     "info": "茅州人氏，梁山泊掌管监造诸事头领，负责军中走报机密步军头领，位列第七十七"},
    {"id": 78, "name": "龚旺", "nick": "花项虎", "atk": 59, "def": 26, "lead": 57, "might": 73, "intel": 29, "politics": 40, "charm": 55,
     "info": "东昌府人氏，梁山泊步军将校，位列第七十八"},
    {"id": 79, "name": "丁得孙", "nick": "中箭虎", "atk": 50, "def": 10, "lead": 55, "might": 73, "intel": 37, "politics": 41, "charm": 45,
     "info": "东昌府人氏，梁山泊步军将校，位列第七十九"},
    {"id": 80, "name": "穆春", "nick": "小遮拦", "atk": 30, "def": 15, "lead": 38, "might": 45, "intel": 24, "politics": 22, "charm": 40,
     "info": "江州揭阳镇人氏，梁山泊步军将校，位列第八十"},
    {"id": 81, "name": "曹正", "nick": "操刀鬼", "atk": 35, "def": 20, "lead": 45, "might": 74, "intel": 78, "politics": 62, "charm": 47,
     "info": "东京人氏，梁山泊掌管监造诸事头领，负责屠宰牛马猪羊牲口，位列第八十一"},
    {"id": 82, "name": "宋万", "nick": "云里金刚", "atk": 46, "def": 33, "lead": 52, "might": 60, "intel": 28, "politics": 21, "charm": 55,
     "info": "祖籍不详（一说济州人氏），梁山泊步军将校，位列第八十二"},
    {"id": 83, "name": "杜迁", "nick": "摸着天", "atk": 47, "def": 32, "lead": 47, "might": 59, "intel": 37, "politics": 30, "charm": 47,
     "info": "祖籍不详（一说济州人氏），梁山泊步军将校，位列第八十三"},
    {"id": 84, "name": "薛永", "nick": "病大虫", "atk": 39, "def": 15, "lead": 32, "might": 65, "intel": 39, "politics": 31, "charm": 42,
     "info": "河南洛阳人氏，梁山泊步军将校，位列第八十四"},
    {"id": 85, "name": "施恩", "nick": "金眼彪", "atk": 25, "def": 15, "lead": 45, "might": 49, "intel": 62, "politics": 67, "charm": 60,
     "info": "孟州人氏，梁山泊步军将校，位列第八十五"},
    {"id": 86, "name": "李忠", "nick": "打虎将", "atk": 44, "def": 22, "lead": 55, "might": 66, "intel": 40, "politics": 41, "charm": 35,
     "info": "濠州定远人氏，梁山泊步军将校，位列第八十六"},
    {"id": 87, "name": "周通", "nick": "小霸王", "atk": 32, "def": 20, "lead": 50, "might": 61, "intel": 24, "politics": 30, "charm": 28,
     "info": "青州人氏，梁山泊步军将校，位列第八十七"},
    {"id": 88, "name": "汤隆", "nick": "金钱豹子", "atk": 42, "def": 36, "lead": 41, "might": 63, "intel": 66, "politics": 69, "charm": 32,
     "info": "延安府人氏，梁山泊掌管监造诸事头领，负责监造军器铁甲，位列第八十八"},
    {"id": 89, "name": "杜兴", "nick": "鬼脸儿", "atk": 47, "def": 28, "lead": 29, "might": 56, "intel": 63, "politics": 77, "charm": 12,
     "info": "中山府人氏，梁山泊掌管监造诸事头领，负责监造梁山泊一应房舍厅堂，位列第八十九"},
    {"id": 90, "name": "邹渊", "nick": "出林龙", "atk": 42, "def": 22, "lead": 52, "might": 66, "intel": 50, "politics": 29, "charm": 58,
     "info": "莱州人氏，梁山泊步军将校，位列第九十"},
    {"id": 91, "name": "邹润", "nick": "独角龙", "atk": 45, "def": 26, "lead": 51, "might": 69, "intel": 39, "politics": 20, "charm": 41,
     "info": "莱州人氏，梁山泊步军将校，位列第九十一"},
    {"id": 92, "name": "朱贵", "nick": "旱地忽律", "atk": 16, "def": 12, "lead": 35, "might": 48, "intel": 65, "politics": 60, "charm": 66,
     "info": "沂州沂水县人氏，梁山泊四店打听声息邀接来宾头领，负责东山酒店，位列第九十二"},
    {"id": 93, "name": "朱富", "nick": "笑面虎", "atk": 42, "def": 26, "lead": 30, "might": 52, "intel": 61, "politics": 62, "charm": 58,
     "info": "沂州沂水县人氏，梁山泊掌管监造诸事头领，负责监造供应酒醋，位列第九十三"},
    {"id": 94, "name": "蔡福", "nick": "铁臂膊", "atk": 20, "def": 15, "lead": 33, "might": 59, "intel": 59, "politics": 48, "charm": 38,
     "info": "北京大名府人氏，梁山泊掌管监造诸事头领，负责专管行刑刽子，位列第九十四"},
    {"id": 95, "name": "蔡庆", "nick": "一枝花", "atk": 20, "def": 15, "lead": 30, "might": 54, "intel": 57, "politics": 40, "charm": 59,
     "info": "北京大名府人氏，梁山泊掌管监造诸事头领，负责专管行刑刽子，位列第九十五"},
    {"id": 96, "name": "李立", "nick": "催命判官", "atk": 41, "def": 21, "lead": 37, "might": 52, "intel": 35, "politics": 38, "charm": 27,
     "info": "江州揭阳岭人氏，梁山泊四店打听声息邀接来宾头领，负责南山酒店，位列第九十六"},
    {"id": 97, "name": "李云", "nick": "青眼虎", "atk": 25, "def": 10, "lead": 60, "might": 66, "intel": 52, "politics": 68, "charm": 65,
     "info": "沂州沂水县人氏，梁山泊掌管监造诸事头领，负责监造梁山泊一应房舍厅堂，位列第九十七"},
    {"id": 98, "name": "焦挺", "nick": "没面目", "atk": 65, "def": 2, "lead": 18, "might": 69, "intel": 30, "politics": 25, "charm": 5,
     "info": "中山府人氏，梁山泊步军将校，位列第九十八"},
    {"id": 99, "name": "石勇", "nick": "石将军", "atk": 15, "def": 15, "lead": 29, "might": 59, "intel": 26, "politics": 28, "charm": 15,
     "info": "北京大名府人氏，梁山泊步军将校，位列第九十九"},
    {"id": 100, "name": "孙新", "nick": "小尉迟", "atk": 30, "def": 10, "lead": 52, "might": 62, "intel": 64, "politics": 60, "charm": 60,
     "info": "琼州人氏，梁山泊四店打听声息邀接来宾头领，负责东山酒店，位列第一百"},
    {"id": 101, "name": "顾大嫂", "nick": "母大虫", "atk": 20, "def": 10, "lead": 58, "might": 64, "intel": 75, "politics": 52, "charm": 76,
     "info": "琼州人氏，梁山泊四店打听声息邀接来宾头领，负责东山酒店，位列第一百零一"},
    {"id": 102, "name": "张青", "nick": "菜园子", "atk": 40, "def": 5, "lead": 32, "might": 57, "intel": 58, "politics": 61, "charm": 42,
     "info": "孟州人氏，梁山泊四店打听声息邀接来宾头领，负责西山酒店，位列第一百零二"},
    {"id": 103, "name": "孙二娘", "nick": "母夜叉", "atk": 7, "def": 15, "lead": 30, "might": 63, "intel": 61, "politics": 63, "charm": 54,
     "info": "孟州人氏，梁山泊四店打听声息邀接来宾头领，负责西山酒店，位列第一百零三"},
    {"id": 104, "name": "王定六", "nick": "活闪婆", "atk": 40, "def": 15, "lead": 21, "might": 47, "intel": 50, "politics": 33, "charm": 38,
     "info": "南京建康府人氏，梁山泊四店打听声息邀接来宾头领，负责北山酒店，位列第一百零四"},
    {"id": 105, "name": "郁保四", "nick": "险道神", "atk": 40, "def": 20, "lead": 22, "might": 68, "intel": 54, "politics": 20, "charm": 62,
     "info": "青州人氏，梁山泊掌管监造诸事头领，负责专一把捧帅字旗，位列第一百零五"},
    {"id": 106, "name": "白胜", "nick": "白日鼠", "atk": 5, "def": 5, "lead": 13, "might": 41, "intel": 61, "politics": 33, "charm": 25,
     "info": "济州石碣村人氏，梁山泊步军将校，位列第一百零六"},
    {"id": 107, "name": "时迁", "nick": "鼓上蚤", "atk": 12, "def": 14, "lead": 3, "might": 47, "intel": 67, "politics": 64, "charm": 6,
     "info": "高唐州人氏，梁山泊四店打听声息邀接来宾头领，负责北山酒店，位列第一百零七"},
    {"id": 108, "name": "段景住", "nick": "金毛犬", "atk": 40, "def": 15, "lead": 15, "might": 48, "intel": 32, "politics": 38, "charm": 12,
     "info": "涿州人氏，梁山泊四店打听声息邀接来宾头领，负责北山酒店，位列第一百零八"},
]

CARD_BY_NAME = {c["name"]: c for c in CARDS}
CARD_BY_ID = {c["id"]: c for c in CARDS}
